<?php
$this->breadcrumbs=array(
	'Image Data',
);

$this->menu=array(
array('label'=>'Image Data Home', 'url'=>array('index'), 'itemOptions'=>array('class'=>'active')),
array('label'=>'Upload Image Data','url'=>array('upload')),
array('label'=>'Image Gallery','url'=>array('gallery')),
array('label'=>'Manage Image Data','url'=>array('admin'))
);
?>

<h3>Image Data</h3>
<hr/>
<p>
The image data module allows users to upload and manage image meta-data collections generated by the <a href="http://www.flickr.com/services/api/">Flickr API</a>.
The data is collected by a crawler designed at the lab which regularly outputs the records as <b>.dump</b> files. These files can be uploaded here and non-redundant
records will be stored. The images and associated meta-data can also be viewed and updated.
</p>